algoritmo "Conte"
var
   Valor, salto, contador: Inteiro
inicio
      Contador <- 0
      escreva("Quer contar ate quanto? ")
      leia(valor)
      escreva("Qual será o valor do salto? ")
      leia(salto)
      Enquanto (contador <= valor) faca
               escreval(contador)
               Contador <- contador + salto
               
      FimEnquanto
      escreval("Terminei de contar")
      
      
      
fimalgoritmo
